### ISSUE TITLE
Compilation Errors after upgrading TS to 5.1.x

### ISSUE THREAD

**Issue by goosewobbler** [webdriverio-community/wdio-electron-service#105]
Upgrading TS to `5.1.x` results in the following compilation errors:

```
error TS2688: Cannot find type definition file for '@wdio/globals/types'.
  The file is in the program because:
    Entry point of type library '@wdio/globals/types' specified in compilerOptions

  tsconfig.json:8:23
    8     "types": ["node", "@wdio/globals/types"]
                            ~~~~~~~~~~~~~~~~~~~~~
    File is entry point of type library specified here.
```
---
```
src/service.ts:179:27 - error TS2684: The 'this' context of type 'WebdriverIO.Browser' is not assignable to method's 'this' of type 'import("<snip />/wdio-electron-service/node_modules/.pnpm/webdriverio@8.13.1_typescript@5.1.6/node_modules/webdriverio/build/types").Browser'.
  Type 'Browser' is missing the following properties from type 'Browser': sessionStatus, sessionNew, sessionEnd, sessionSubscribe, and 25 more.

179             return await (browser.executeAsync as WebdriverClientFunc)(callApi, bridgeProp, args);
                              ~~~~~~~
```
---
```
src/service.ts:179:27 - error TS2352: Conversion of type '<ReturnValue, InnerArguments extends any[]>(this: Browser | Element, script: string | ((...args: [...innerArgs: InnerArguments, callback: (result?: ReturnValue | undefined) => void]) => void), ...args: InnerArguments) => Promise<...>' to type 'WebdriverClientFunc' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  The 'this' types of each signature are incompatible.
    Type 'Browser' is not comparable to type 'Browser | Element'.
      Type 'Browser' is missing the following properties from type 'Element': elementId, ELEMENT, selector, parent, and 38 more.

179             return await (browser.executeAsync as WebdriverClientFunc)(callApi, bridgeProp, args);
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
